Repository nativescript-community/nativescript-vscode-extension, pull requests merged in 2019-03, with the labels that each got.

#241 fix: use strict versions for all dependencies
  package.json
Labels: cla: yes, new PR

#242 release: cut 0.9.0 release
  CHANGELOG.md
  package.json
Labels: cla: yes, new PR

#231 update LICENSE year
  LICENSE
Labels: cla: yes, new PR

#243 chore: update chrome-debug-adapter to latest version
  package.json
  src/debug-adapter/nativeScriptDebugAdapter.ts
  src/debug-adapter/nativeScriptPathTransformer.ts
  src/debug-adapter/nativeScriptTargetDiscovery.ts
  src/tests/nativeScriptPathTransformer.tests.ts
Labels: cla: yes

#244 feat: add support for debug with hmr
  package.json
  src/debug-adapter/nativeScriptDebug.ts
  src/debug-adapter/nativeScriptDebugAdapter.ts
  src/debug-adapter/nativeScriptPathTransformer.ts
  src/debug-adapter/nativeScriptSourceMapTransformer.ts
  src/main.ts
  src/tests/nativeScriptDebugAdapter.tests.ts
Labels: cla: yes, feature, new PR

#245 fix: debug-brk does not work with webpack
  src/debug-adapter/nativeScriptPathTransformer.ts
  src/tests/nativeScriptPathTransformer.tests.ts
  src/tests/pathTransformData.ts
Labels: bug, new PR

#247 relese: cut 0.10.0
  CHANGELOG.md
  package.json
Labels: new PR
